export interface AIProviderResponse {
  content: string;
  tokensUsed: {
    input: number;
    output: number;
    total: number;
  };
}

export interface AIProvider {
  generateText(prompt: string, context?: string): Promise<AIProviderResponse>;
}

export class MockAIProvider implements AIProvider {
  async generateText(prompt: string, context?: string): Promise<AIProviderResponse> {
    // In a real mock, we would parse the prompt and return deterministic mock output.
    // For Phase 9 demonstration, we return a standard mock response.
    const mockContent = `[MOCK AI RESPONSE]\n\nBased on your input:\n"${prompt.substring(0, 50)}..."\n\nHere is a suggested structure:\n1. Precondition: User is logged in.\n2. Step: Click the 'Test' button.\n3. Expected: The system responds correctly.\n\n*Note: This is an advisory suggestion generated by the Mock AI Provider.*`;
    
    return {
      content: mockContent,
      tokensUsed: {
        input: 10,
        output: 50,
        total: 60
      }
    };
  }
}
